### ISSUE TITLE
Items for v 0.2 Spec

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/Resource-Container#2]
- [x] Switch to YAML for manifest
- [x] Specify content encoding
- [x] Use Dublin Core metadata
- [x] Specify that file extension doesn't matter, list recommended formats (git, zip, etc)
- [x] Make `media` a full fledged resource type and update linking to match
- [x] Link to examples of the container on Gogs (English OBS, tW, tQ)
- [x] Link to example parsers
- [x] Add `check` type ?

**Comment by neutrinog** [comment]
we might want to revisit how link arguments are handled. Right now it's taking things like `01:01-02` which looks great to a user but is not proper url syntax. We don't technically need to support the RFC for url syntax but it would make things more consistent/universal.

**Comment by neutrinog** [comment]
in the sample parsers (the android and node modules) we should remove the compression code entirely and allow the user to extract the resource containers as needed. This will the need to maintain already known compression techniques, simplify the modules, and provide better abstraction.
